/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAppWalletsRouteImport } from './routes/_authenticated/app.wallets'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/app.support'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppMarketRouteImport } from './routes/_authenticated/app.market'
import { Route as AuthenticatedAppInvestRouteImport } from './routes/_authenticated/app.invest'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin.transactions'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin.tickets'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminKycRouteImport } from './routes/_authenticated/admin.kyc'
import { Route as AuthenticatedAdminCurrenciesRouteImport } from './routes/_authenticated/admin.currencies'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin.clients.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedAppSupportTicketIdRouteImport } from './routes/_authenticated/app.support.$ticketId'
import { Route as AuthenticatedAdminTicketsTicketIdRouteImport } from './routes/_authenticated/admin.tickets.$ticketId'
import { Route as AuthenticatedAdminClientsUserIdRouteImport } from './routes/_authenticated/admin.clients.$userId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppWalletsRoute = AuthenticatedAppWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMarketRoute = AuthenticatedAppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInvestRoute = AuthenticatedAppInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKycRoute = AuthenticatedAdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCurrenciesRoute =
  AuthenticatedAdminCurrenciesRouteImport.update({
    id: '/currencies',
    path: '/currencies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSupportTicketIdRoute =
  AuthenticatedAppSupportTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedAppSupportRoute,
  } as any)
const AuthenticatedAdminTicketsTicketIdRoute =
  AuthenticatedAdminTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedAdminTicketsRoute,
  } as any)
const AuthenticatedAdminClientsUserIdRoute =
  AuthenticatedAdminClientsUserIdRouteImport.update({
    id: '/clients/$userId',
    path: '/clients/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agent': typeof AuthenticatedAgentRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/currencies': typeof AuthenticatedAdminCurrenciesRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRouteWithChildren
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/app/invest': typeof AuthenticatedAppInvestRoute
  '/app/market': typeof AuthenticatedAppMarketRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/support': typeof AuthenticatedAppSupportRouteWithChildren
  '/app/wallets': typeof AuthenticatedAppWalletsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/clients/$userId': typeof AuthenticatedAdminClientsUserIdRoute
  '/admin/tickets/$ticketId': typeof AuthenticatedAdminTicketsTicketIdRoute
  '/app/support/$ticketId': typeof AuthenticatedAppSupportTicketIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/currencies': typeof AuthenticatedAdminCurrenciesRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRouteWithChildren
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/app/invest': typeof AuthenticatedAppInvestRoute
  '/app/market': typeof AuthenticatedAppMarketRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/support': typeof AuthenticatedAppSupportRouteWithChildren
  '/app/wallets': typeof AuthenticatedAppWalletsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/clients/$userId': typeof AuthenticatedAdminClientsUserIdRoute
  '/admin/tickets/$ticketId': typeof AuthenticatedAdminTicketsTicketIdRoute
  '/app/support/$ticketId': typeof AuthenticatedAppSupportTicketIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/currencies': typeof AuthenticatedAdminCurrenciesRoute
  '/_authenticated/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRouteWithChildren
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/app/invest': typeof AuthenticatedAppInvestRoute
  '/_authenticated/app/market': typeof AuthenticatedAppMarketRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/support': typeof AuthenticatedAppSupportRouteWithChildren
  '/_authenticated/app/wallets': typeof AuthenticatedAppWalletsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/clients/$userId': typeof AuthenticatedAdminClientsUserIdRoute
  '/_authenticated/admin/tickets/$ticketId': typeof AuthenticatedAdminTicketsTicketIdRoute
  '/_authenticated/app/support/$ticketId': typeof AuthenticatedAppSupportTicketIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/agent'
    | '/app'
    | '/dashboard'
    | '/admin/currencies'
    | '/admin/kyc'
    | '/admin/logs'
    | '/admin/plans'
    | '/admin/team'
    | '/admin/tickets'
    | '/admin/transactions'
    | '/app/invest'
    | '/app/market'
    | '/app/profile'
    | '/app/support'
    | '/app/wallets'
    | '/admin/'
    | '/app/'
    | '/admin/clients/$userId'
    | '/admin/tickets/$ticketId'
    | '/app/support/$ticketId'
    | '/lovable/email/queue/process'
    | '/admin/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/agent'
    | '/dashboard'
    | '/admin/currencies'
    | '/admin/kyc'
    | '/admin/logs'
    | '/admin/plans'
    | '/admin/team'
    | '/admin/tickets'
    | '/admin/transactions'
    | '/app/invest'
    | '/app/market'
    | '/app/profile'
    | '/app/support'
    | '/app/wallets'
    | '/admin'
    | '/app'
    | '/admin/clients/$userId'
    | '/admin/tickets/$ticketId'
    | '/app/support/$ticketId'
    | '/lovable/email/queue/process'
    | '/admin/clients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/agent'
    | '/_authenticated/app'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/currencies'
    | '/_authenticated/admin/kyc'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/app/invest'
    | '/_authenticated/app/market'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/support'
    | '/_authenticated/app/wallets'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/clients/$userId'
    | '/_authenticated/admin/tickets/$ticketId'
    | '/_authenticated/app/support/$ticketId'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/wallets': {
      id: '/_authenticated/app/wallets'
      path: '/wallets'
      fullPath: '/app/wallets'
      preLoaderRoute: typeof AuthenticatedAppWalletsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/support': {
      id: '/_authenticated/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/market': {
      id: '/_authenticated/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AuthenticatedAppMarketRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invest': {
      id: '/_authenticated/app/invest'
      path: '/invest'
      fullPath: '/app/invest'
      preLoaderRoute: typeof AuthenticatedAppInvestRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kyc': {
      id: '/_authenticated/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AuthenticatedAdminKycRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/currencies': {
      id: '/_authenticated/admin/currencies'
      path: '/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AuthenticatedAdminCurrenciesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/support/$ticketId': {
      id: '/_authenticated/app/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/app/support/$ticketId'
      preLoaderRoute: typeof AuthenticatedAppSupportTicketIdRouteImport
      parentRoute: typeof AuthenticatedAppSupportRoute
    }
    '/_authenticated/admin/tickets/$ticketId': {
      id: '/_authenticated/admin/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedAdminTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedAdminTicketsRoute
    }
    '/_authenticated/admin/clients/$userId': {
      id: '/_authenticated/admin/clients/$userId'
      path: '/clients/$userId'
      fullPath: '/admin/clients/$userId'
      preLoaderRoute: typeof AuthenticatedAdminClientsUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminTicketsRouteChildren {
  AuthenticatedAdminTicketsTicketIdRoute: typeof AuthenticatedAdminTicketsTicketIdRoute
}

const AuthenticatedAdminTicketsRouteChildren: AuthenticatedAdminTicketsRouteChildren =
  {
    AuthenticatedAdminTicketsTicketIdRoute:
      AuthenticatedAdminTicketsTicketIdRoute,
  }

const AuthenticatedAdminTicketsRouteWithChildren =
  AuthenticatedAdminTicketsRoute._addFileChildren(
    AuthenticatedAdminTicketsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCurrenciesRoute: typeof AuthenticatedAdminCurrenciesRoute
  AuthenticatedAdminKycRoute: typeof AuthenticatedAdminKycRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRouteWithChildren
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientsUserIdRoute: typeof AuthenticatedAdminClientsUserIdRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCurrenciesRoute: AuthenticatedAdminCurrenciesRoute,
  AuthenticatedAdminKycRoute: AuthenticatedAdminKycRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRouteWithChildren,
  AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClientsUserIdRoute: AuthenticatedAdminClientsUserIdRoute,
  AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppSupportRouteChildren {
  AuthenticatedAppSupportTicketIdRoute: typeof AuthenticatedAppSupportTicketIdRoute
}

const AuthenticatedAppSupportRouteChildren: AuthenticatedAppSupportRouteChildren =
  {
    AuthenticatedAppSupportTicketIdRoute: AuthenticatedAppSupportTicketIdRoute,
  }

const AuthenticatedAppSupportRouteWithChildren =
  AuthenticatedAppSupportRoute._addFileChildren(
    AuthenticatedAppSupportRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppInvestRoute: typeof AuthenticatedAppInvestRoute
  AuthenticatedAppMarketRoute: typeof AuthenticatedAppMarketRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRouteWithChildren
  AuthenticatedAppWalletsRoute: typeof AuthenticatedAppWalletsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppInvestRoute: AuthenticatedAppInvestRoute,
  AuthenticatedAppMarketRoute: AuthenticatedAppMarketRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRouteWithChildren,
  AuthenticatedAppWalletsRoute: AuthenticatedAppWalletsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
